china_cities = frozenset(
    [
        "anqing",
        "bengbu",
        "hefei",
        "huainan",
        "huangshan",
        "ma’anshan",
        "shexian",
        "tongcheng",
        "tongling",
        "wuhu",
        "xuancheng",
        "beijing",
        "chongqing",
        "hechuan",
        "wanzhou",
        "fuzhou",
        "longyan",
        "nanping",
        "quanzhou",
        "sanming",
        "shaowu",
        "xiamen",
        "yong’an",
        "zhangzhou",
        "dunhuang",
        "jiuquan",
        "lanzhou",
        "pingliang",
        "tianshui",
        "wuwei",
        "yumen",
        "chaozhou",
        "foshan",
        "guangzhou",
        "jiangmen",
        "maoming",
        "meizhou",
        "shantou",
        "shaoguan",
        "shenzhen",
        "zhanjiang",
        "zhaoqing",
        "zhongshan",
        "baise",
        "beihai",
        "guilin",
        "liuzhou",
        "nanning",
        "pingxiang",
        "wuzhou",
        "yulin",
        "anshun",
        "duyun",
        "guiyang",
        "zunyi",
        "haikou",
        "baoding",
        "cangzhou",
        "chengde",
        "handan",
        "kalgan",
        "qinhuangdao",
        "shanhaiguan",
        "shijiazhuang",
        "tangshan",
        "xingtai",
        "xuanhua",
        "zhengding",
        "acheng",
        "binxian",
        "harbin",
        "hegang",
        "hulan",
        "jiamusi",
        "jixi",
        "mudanjiang",
        "qiqihar",
        "shuangyashan",
        "yichun",
        "anyang",
        "hebi",
        "jiaozuo",
        "kaifeng",
        "luohe",
        "luoyang",
        "nanyang",
        "shangqiu",
        "xinxiang",
        "xinyang",
        "xuchang",
        "zhengzhou",
        "zhoukou",
        "hongkong",
        "victoria",
        "daye",
        "hankou",
        "hanyang",
        "huangshi",
        "jingzhou",
        "laohekou",
        "wuchang",
        "wuhan",
        "xiangfan",
        "yichang",
        "changde",
        "changsha",
        "hengyang",
        "jinshi",
        "shaoyang",
        "xiangtan",
        "yiyang",
        "yueyang",
        "zhuzhou",
        "baotou",
        "chifeng",
        "duolun",
        "erenhot",
        "hailar",
        "hohhot",
        "jining",
        "manzhouli",
        "tongliao",
        "changshu",
        "changzhou",
        "huai’an",
        "huaiyin",
        "lianyungang",
        "nanjing",
        "nantong",
        "suzhou",
        "taizhou",
        "wuxi",
        "xuzhou",
        "yancheng",
        "yangzhou",
        "zhenjiang",
        "ganzhou",
        "ji’an",
        "jingdezhen",
        "jiujiang",
        "nanchang",
        "pingxiang",
        "shangrao",
        "zhangshu",
        "baicheng",
        "changchun",
        "jilin",
        "liaoyuan",
        "siping",
        "tonghua",
        "yanji",
        "anshan",
        "beipiao",
        "benxi",
        "dalian",
        "dandong",
        "fushun",
        "fuxin",
        "liaoyang",
        "lüshun",
        "shenyang",
        "wafangdian",
        "yingkou",
        "macau",
        "yinchuan",
        "golmud",
        "lenghu",
        "xining",
        "ankang",
        "baoji",
        "hanzhong",
        "shangluo",
        "tongguan",
        "xi’an",
        "xianyang",
        "yan’an",
        "dezhou",
        "jinan",
        "jining",
        "linzi",
        "qingdao",
        "qufu",
        "weifang",
        "weihai",
        "yantai",
        "zaozhuang",
        "zibo",
        "shanghai",
        "changzhi",
        "datong",
        "jinzhong",
        "linfen",
        "puzhou",
        "taiyuan",
        "yangquan",
        "chengdu",
        "kangding",
        "luzhou",
        "mianyang",
        "nanchong",
        "neijiang",
        "wutongqiao",
        "ya’an",
        "yibin",
        "zigong",
        "tanggu",
        "tianjin",
        "gartok",
        "gyangzê",
        "lhasa",
        "xigazê",
        "hami",
        "hotan",
        "karamay",
        "kashgar",
        "kucha",
        "kuldja",
        "shihezi",
        "turfan",
        "ürümqi",
        "yarkand",
        "dali",
        "gejiu",
        "jinghong",
        "kaiyuan",
        "kunming",
        "pu’er",
        "fenghua",
        "hangzhou",
        "huzhou",
        "jiaxing",
        "jinhua",
        "ningbo",
        "quzhou",
        "shaoxing",
        "wenzhou",
    ]
)

north_a_map = {
    "belize": "BLZ",
    "canada": "CAN",
    "costa_rica": "CRI",
    "cuba": "CUB",
    "dominican_republic": "DOM",
    "guatemala": "GTM",
    "jamaica": "JAM",
    "mexico": "MEX",
    "panama": "PAN",
    "usa": "USA",
    "puerto_rico": "USA",
}

africa_map = {
    "algeria": "DZA",
    "benin": "BEN",
    "botswana": "BWA",
    "cameroon": "CMR",
    "drc": "COD",
    "democratic_republic_of_the_congo": "COD",
    "egypt": "EGY",
    "gabon": "GAB",
    "gambia": "GMB",
    "ghana": "GHA",
    "kenya": "KEN",
    "madagascar": "MDG",
    "mali": "MLI",
    "morocco": "MAR",
    "nigeria": "NGA",
    "reunion": "REU",
    "senegal": "SEN",
    "sierra_leone": "SLE",
    "south_africa": "ZAF",
    "tunisia": "TUN",
    "uganda": "UGA",
    "zambia": "ZMB",
}

south_a_map = {
    "argentina": "ARG",
    "aruba": "ABW",
    "brazil": "BRA",
    "chile": "CHL",
    "colombia": "COL",
    "curacao": "NLD",
    "ecuador": "ECU",
    "peru": "PER",
    "suriname": "SUR",
    "uruguay": "URY",
    "venezuela": "VEN",
}

europe_map = {
    "andorra": "AND",
    "austria": "AUT",
    "belarus": "BLR",
    "belgium": "BEL",
    "bosnia_and_herzegovina": "BIH",
    "bulgaria": "BGR",
    "crimea": "RUS",
    "croatia": "HRV",
    "cyprus": "CYP",
    "czech_republic": "CZE",
    "denmark": "DNK",
    "estonia": "EST",
    "faroe_islands": "FRO",
    "finland": "FIN",
    "france": "FRA",
    "germany": "DEU",
    "gibraltar": "GIB",
    "greece": "GRC",
    "hungary": "HUN",
    "iceland": "ISL",
    "ireland": "IRL",
    "italy": "ITA",
    "latvia": "LVA",
    "lithuania": "LTU",
    "luxembourg": "LUX",
    "malta": "MLT",
    "moldova": "MDA",
    "montenegro": "MNE",
    "netherlands": "NLD",
    "north_macedonia": "MKD",
    "norway": "NOR",
    "poland": "POL",
    "portugal": "PRT",
    "romania": "ROU",
    "russia": "RUS",
    "serbia": "SRB",
    "slovakia": "SVK",
    "slovenia": "SVN",
    "spain": "ESP",
    "sweden": "SWE",
    "switzerland": "CHE",
    "turkey": "TUR",
    "ukraine": "UKR",
    "united_kingdom": "GBR",
    "uk": "GBR",
    "scotland": "GBR",
    "northern_ireland": "GBR",
    "wales": "GBR",
    "england": "GBR",
}

asia_map = {
    "bahrain": "BHR",
    "bahrein": "BHR",
    "bangladesh": "BGD",
    "brunei": "BRN",
    "cambodia": "KHM",
    "china": "CHN",
    "georgia": "GEO",
    "hong_kong": "HKG",
    "india": "IND",
    "indonesia": "IDN",
    "iran": "IRN",
    "iraq": "IRQ",
    "israel": "ISR",
    "japan": "JPN",
    "jordan": "JOR",
    "kazakhstan": "KAZ",
    "kuwait": "KWT",
    "lebanon": "LBN",
    "malaysia": "MYS",
    "mongolia": "MNG",
    "myanmar": "MMR",
    "nepal": "NPL",
    "oman": "OMN",
    "pakistan": "PAK",
    "philippines": "PHL",
    "qatar": "QAT",
    "saudi_arabia": "SAU",
    "saudiarabia": "SAU",
    "singapore": "SGP",
    "south_korea": "KOR",
    "sri_lanka": "LKA",
    "taiwan": "TWN",
    "thailand": "THA",
    "timor-leste": "TLS",
    "united_arab_emirates": "ARE",
    "uzbekistan": "UZB",
    "vietnam": "VNM",
}

oceania_map = {
    "new_zealand": "NZL",
    "australia": "AUS",
    "guam": "GUM",
}


class CountryAlphaMap:
    """
    Maps a country name to its corresponding Alpha 3 code
    """

    @staticmethod
    def getCode(country_name: str) -> str:
        """
        Args;

            - country_name (str): country_name should be all lower case and have "_" in place of " ".

        Returns:

            - str: country name with proper capitalization
            - str: country's corresponding alpha 3 code
        """
        maps = [africa_map, europe_map, south_a_map, north_a_map, asia_map, oceania_map]
        country = "China"
        iso_a3 = "CHN"
        for continent in maps:
            actl_iso = continent.get(country_name, "")

            if actl_iso:
                country = " ".join(
                    map(lambda x: x.capitalize(), country_name.split("_"))
                )
                country = "Saudi Arabia" if country == "Saudiarabia" else country

                iso_a3 = actl_iso
                break

        return (country, iso_a3)
